[package]
name = "porchetta"
version = "0.1.0"
edition = "2024"

[lints.clippy]
all = "warn"
perf = "warn"
pedantic = "warn"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
gix = { version = "0.81.0", features = ["merge"] }
hostname = "0.4.2"
log = "0.4.29"
mlua = { version = "0.11.6", features = ["anyhow", "lua54", "vendored"] }
tempfile = "3.27.0"
smallvec = "1.13"
inquire = "0.9.4"
flexi_logger = "0.31"
dirs = "6"
owo-colors = "4"
camino = "1.2"
